### ISSUE TITLE
farmOS Guide Menu View

### ISSUE THREAD

**Issue by asubers** [farmOS/farmOS.org#85] opened 2023-10-17 17:14 UTC
The view of the menu on the left hand side on the farmOS guide page is not working correctly. The down arrows are in front of the text and the words are long and you need to scroll left and right to see the whole word in the menu. 

I am using Chrome on a MacBook Pro. 

![Screen Shot 2023-10-17 at 9 41 36 AM](https://github.com/farmOS/farmOS.org/assets/148263956/778950d3-2089-4040-b183-58bf52e47fc2)
![Screen Shot 2023-10-17 at 9 42 46 AM](https://github.com/farmOS/farmOS.org/assets/148263956/9729886d-e3de-4143-80db-a87150763d0a)

**Comment by mstenta** [comment] 2023-10-17 17:16
Hmm I wonder if this is a Chrome issue? Curious if others are seeing it.

In Firefox (on Debian) it looks OK:

![Screenshot 2023-10-17 at 12-54-52 farmOS User Guide](https://github.com/farmOS/farmOS.org/assets/95381/9de4c274-7c92-4799-9558-d24f81f28c23)

**Comment by mstenta** [comment] 2023-10-19 14:18
I had a friend check on their Mac (OS X 13.2 + Chrome 116) and they said it is not broken for them.

Another user in farmOS chat (@mseverething) also tested in Chrome (not sure what OS) and said they didn't experience the issue either.

I'm not sure why you're experiencing it @asubers... :thinking:

**Comment by mstenta** [comment] 2023-10-19 14:20
I'm going to close this as "can't reproduce" just so it isn't left hanging in the issue queue, but I will continue to ask others to test, and if anyone else is experiencing it I will reopen. Maybe we can investigate on your end together sometime @asubers - but it seems like this isn't an issue with farmOS specifically.

**Closed as not planned by mstenta** 2023-10-19 14:20 UTC
Labels: bug
